<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestCeleryMethods-20181115150120" tests="2" time="0.123">
	<testcase classname="TestCeleryMethods" name="test_n1" time="0.107"/>
	<testcase classname="TestCeleryMethods" name="test_n1_1" time="0.016">
		<error message="0 != 1" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "c:/Users/henry.wang/Desktop/Henry/Pilots/celeryvenv/tests.py", line 11, in test_n1_1
    self.assertEqual(run_tasks.func_run_tasks(), 1)
AssertionError: 0 != 1
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[0 03d7b970-8f0e-4b6a-ad04-95396d1a0cb9
1 56dffd20-4f8a-4030-9d93-a8f0899493f0
2 f497e9ef-6814-4cb5-ae9f-90e559b9f12d
3 c7be17e1-fc68-4850-b5f7-6de92b62e323
4 9d4a001d-74d4-4907-9ebf-9188dbb51b7d
5 924aac4b-c372-447d-8faf-2c8cdfbd369a
6 e9a77309-dc95-4d8e-9403-6c9952b02bfd
7 fd78f9f3-3aa0-4536-96f8-317884b01b8c
8 04d2a255-0428-4d03-9e62-6058bbac17fa
9 07a7bb3a-7118-407b-a0f0-ce404f56d1b8
0 37500763-73ec-4515-a755-d61b1269ad62
1 2c5061be-e91b-456f-8a07-301be873c7e3
2 2ed056c3-b759-415d-b6ff-88a5f8606423
3 2aa5501e-de97-46c1-aa90-53082a3946fe
4 a43f0c05-57bc-46b1-89d2-19b696cd1df2
5 99d67385-6ac1-43f1-846a-a9dafc6a1e8d
6 636b2eb0-c231-4010-88ed-acc3fcd5e197
7 650063f8-c0b9-4a1f-866a-304fe7de7efe
8 7ec12784-29ea-430a-8440-5a977624d6e8
9 ccaa5000-8d9a-41ab-ae3e-6c773b704db1
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
